### ISSUE TITLE
Improve Minikube Test Setup with regards to self signed certificates

### ISSUE THREAD

**Issue by jfaltermeier** [eclipsesource/theia-cloud#165]
### Is your feature request related to a problem? Please describe.

Currently we use a Cluster Issuer like this for testing
```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.issuerstaging.name }}
spec:
  selfSigned: {}
```
The self signed certificates are not trusted be default, which can lead to errors. 

### Describe the solution you'd like

We need a way to create a local test setup that does not run into errors about untrusted certificates. 
Possible solutions could be to configure the trust store or to provide some trusted test certificate. 

### Describe alternatives you've considered

-
