### ISSUE TITLE
Deployments without OAuth Proxy don't set securityContext

### ISSUE THREAD

**Issue by jfaltermeier** [eclipsesource/theia-cloud#176]
### Describe the bug

The `templateDeploymentWithoutOAuthProxy.yaml` misses the `securityContext` configuration:
```
          securityContext:
            runAsUser: placeholder-uid
            runAsGroup: placeholder-uid
      securityContext:
        fsGroup: placeholder-uid
```

When a persisted storage is added to a deployment like this, the permissions are not as expected. 

### Expected behavior

Volume mounts should have the correct access permissions.
