### ISSUE TITLE
Fix generation of names for k8s resources

### ISSUE THREAD

**Issue by jfaltermeier** [eclipsesource/theia-cloud#71]
Names have to follow these conventions:
* contain at most 63 characters
* contain only lowercase alphanumeric characters or '-'
* start with an alphanumeric character
* end with an alphanumeric character

Also they have to be unique. 

At the moment there may be cases where we have duplicate names, e.g. when generating the names for configmaps:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: ws-1660897383007theia-cloud-demo-john-doe-greatcompany-session
  labels:
    theiacloud: emails
...
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ws-1660897383007theia-cloud-demo-john-doe-greatcompany-session
  labels:
    theiacloud: proxy
...
```
For these cases the suffix is lost at the moment.

Affected versions are 0.8.0.MS3 and 0.8.0.MS4
